# Generated by Django 3.0.6 on 2020-07-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200712_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Contact_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Cost_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Description_9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Art_Work_Title_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Blurb_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_1',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_10',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_2',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_3',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_4',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_5',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_6',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_7',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_8',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Hover_Pic_9',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_1',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_10',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_2',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_3',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_4',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_5',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_6',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_7',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_8',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Large_Pic_9',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_1',
            field=models.ImageField(blank=True, default='static/images/location.png', null=True, upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_10',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_2',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_3',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_4',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_5',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_6',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_7',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_8',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_Small_Pic_9',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='artists_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
