# Generated by Django 3.0.6 on 2020-07-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_1', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_2', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_3', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_4', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_5', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_6', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_7', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_8', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_9', models.CharField(blank=True, max_length=100)),
                ('Sust_Blurb_10', models.CharField(blank=True, max_length=100)),
                ('Sust_Small_Pic_1', models.ImageField(blank=True, default='static/images/location.png', null=True, upload_to='Susts_pics')),
                ('Sust_Small_Pic_2', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_3', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_4', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_5', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_6', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_7', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_8', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_9', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Small_Pic_10', models.ImageField(blank=True, default='static/images/location.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_1', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_2', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_3', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_4', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_5', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_6', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_7', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_8', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_9', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Hover_Pic_10', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_1', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_2', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_3', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_4', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_5', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_6', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_7', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_8', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_9', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Large_Pic_10', models.ImageField(blank=True, default='/static/images/150.png', upload_to='Susts_pics')),
                ('Sust_Title_1', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_2', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_3', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_4', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_5', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_6', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_7', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_8', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_9', models.CharField(blank=True, max_length=100)),
                ('Sust_Title_10', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_1', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_2', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_3', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_4', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_5', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_6', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_7', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_8', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_9', models.CharField(blank=True, max_length=100)),
                ('Sust_Date_10', models.CharField(blank=True, max_length=100)),
                ('Sust_Description_1', models.TextField(blank=True)),
                ('Sust_Description_2', models.TextField(blank=True)),
                ('Sust_Description_3', models.TextField(blank=True)),
                ('Sust_Description_4', models.TextField(blank=True)),
                ('Sust_Description_5', models.TextField(blank=True)),
                ('Sust_Description_6', models.TextField(blank=True)),
                ('Sust_Description_7', models.TextField(blank=True)),
                ('Sust_Description_8', models.TextField(blank=True)),
                ('Sust_Description_9', models.TextField(blank=True)),
                ('Sust_Description_10', models.TextField(blank=True)),
                ('Sust_Description_11', models.TextField(blank=True)),
                ('Sust_Description_12', models.TextField(blank=True)),
                ('Sust_Description_13', models.TextField(blank=True)),
                ('Sust_Description_14', models.TextField(blank=True)),
                ('Sust_Description_15', models.TextField(blank=True)),
                ('Sust_Description_16', models.TextField(blank=True)),
                ('Sust_Description_17', models.TextField(blank=True)),
                ('Sust_Description_18', models.TextField(blank=True)),
                ('Sust_Description_19', models.TextField(blank=True)),
                ('Sust_Description_20', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_1',
            new_name='Show_Blurb_1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_10',
            new_name='Show_Blurb_10',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_2',
            new_name='Show_Blurb_2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_3',
            new_name='Show_Blurb_3',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_4',
            new_name='Show_Blurb_4',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_5',
            new_name='Show_Blurb_5',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_6',
            new_name='Show_Blurb_6',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_7',
            new_name='Show_Blurb_7',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_8',
            new_name='Show_Blurb_8',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Blurb_9',
            new_name='Show_Blurb_9',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_1',
            new_name='Show_Date_1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_10',
            new_name='Show_Date_10',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_2',
            new_name='Show_Date_2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_3',
            new_name='Show_Date_3',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_4',
            new_name='Show_Date_4',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_5',
            new_name='Show_Date_5',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_6',
            new_name='Show_Date_6',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_7',
            new_name='Show_Date_7',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_8',
            new_name='Show_Date_8',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Date_9',
            new_name='Show_Date_9',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_1',
            new_name='Show_Description_1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_10',
            new_name='Show_Description_10',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_11',
            new_name='Show_Description_11',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_12',
            new_name='Show_Description_12',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_13',
            new_name='Show_Description_13',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_14',
            new_name='Show_Description_14',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_15',
            new_name='Show_Description_15',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_17',
            new_name='Show_Description_16',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_16',
            new_name='Show_Description_17',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_18',
            new_name='Show_Description_18',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_19',
            new_name='Show_Description_19',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_20',
            new_name='Show_Description_2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_2',
            new_name='Show_Description_20',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_3',
            new_name='Show_Description_3',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_4',
            new_name='Show_Description_4',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_6',
            new_name='Show_Description_5',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_5',
            new_name='Show_Description_6',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_8',
            new_name='Show_Description_7',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_7',
            new_name='Show_Description_8',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Description_9',
            new_name='Show_Description_9',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_1',
            new_name='Show_Title_1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_2',
            new_name='Show_Title_10',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_10',
            new_name='Show_Title_2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_3',
            new_name='Show_Title_3',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_4',
            new_name='Show_Title_4',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_6',
            new_name='Show_Title_5',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_5',
            new_name='Show_Title_6',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_7',
            new_name='Show_Title_7',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_8',
            new_name='Show_Title_8',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Sust_Title_9',
            new_name='Show_Title_9',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_1',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_10',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_2',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_3',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_4',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_5',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_6',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_7',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_8',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Hover_Pic_9',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_1',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_10',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_2',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_3',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_4',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_5',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_6',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_7',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_8',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Large_Pic_9',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_1',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_10',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_2',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_3',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_4',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_5',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_6',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_7',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_8',
        ),
        migrations.RemoveField(
            model_name='show',
            name='Sust_Small_Pic_9',
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_1',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_10',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_2',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_3',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_4',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_5',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_6',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_7',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_8',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Hover_Pic_9',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_1',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_10',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_2',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_3',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_4',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_5',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_6',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_7',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_8',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Large_Pic_9',
            field=models.ImageField(blank=True, default='/static/images/150.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_1',
            field=models.ImageField(blank=True, default='static/images/location.png', null=True, upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_10',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_2',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_3',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_4',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_5',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_6',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_7',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_8',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
        migrations.AddField(
            model_name='show',
            name='Show_Small_Pic_9',
            field=models.ImageField(blank=True, default='static/images/location.png', upload_to='Shows_pics'),
        ),
    ]
