from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
	title = models.CharField(max_length = 100, blank = True)
	date_posted = models.DateTimeField()
	content = models.TextField( blank = True)
	post_pic = models.ImageField(default='static/images/location.png', upload_to = 'post_pics', blank = True)

	def __str__(self):
		return self.title

class Artist(models.Model):

	name = models.CharField(max_length = 100, blank = True)

	Artist_Blurb_1 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_2 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_3 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_4 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_5 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_6 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_7 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_8 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_9 = models.CharField(max_length = 100, blank = True)
	Artist_Blurb_10 = models.CharField(max_length = 100, blank = True)

	Artist_Small_Pic_1 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True, null = True)
	Artist_Small_Pic_2 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_3 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_4 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_5 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_6 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_7 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_8 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_9 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)
	Artist_Small_Pic_10 = models.ImageField(default='static/images/location.png', upload_to = 'artists_pics', blank = True)

	Artist_Hover_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Hover_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)

	Artist_Large_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)
	Artist_Large_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'artists_pics', blank = True)

	Art_Work_Title_1 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_2 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_3 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_4 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_5 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_6 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_7 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_8 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_9 = models.CharField(max_length = 100, blank = True)
	Art_Work_Title_10 = models.CharField(max_length = 100, blank = True)

	Art_Work_Description_1 = models.TextField( blank = True)
	Art_Work_Description_2 = models.TextField(blank = True)
	Art_Work_Description_3 = models.TextField(blank = True)
	Art_Work_Description_4 = models.TextField(blank = True)
	Art_Work_Description_5 = models.TextField(blank = True)
	Art_Work_Description_6 = models.TextField(blank = True)
	Art_Work_Description_7 = models.TextField(blank = True)
	Art_Work_Description_8 = models.TextField(blank = True)
	Art_Work_Description_9 = models.TextField(blank = True)
	Art_Work_Description_10 = models.TextField(blank = True)

	Art_Work_Cost_1 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_2 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_3 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_4 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_5 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_6 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_7 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_8 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_9 = models.CharField(max_length = 100, blank = True)
	Art_Work_Cost_10 = models.CharField(max_length = 100, blank = True)

	Art_Work_Contact_1 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_2 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_3 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_4 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_5 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_6 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_7 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_8 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_9 = models.CharField(max_length = 100, blank = True)
	Art_Work_Contact_10 = models.CharField(max_length = 100, blank = True)

	def __str__(self):
		return self.name

class Show(models.Model):

	name = models.CharField(max_length = 100, blank = True)

	Show_Blurb_1 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_2 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_3 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_4 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_5 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_6 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_7 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_8 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_9 = models.CharField(max_length = 100, blank = True)
	Show_Blurb_10 = models.CharField(max_length = 100, blank = True)

	Show_Small_Pic_1 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True, null = True)
	Show_Small_Pic_2 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_3 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_4 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_5 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_6 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_7 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_8 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_9 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)
	Show_Small_Pic_10 = models.ImageField(default='static/images/location.png', upload_to = 'Shows_pics', blank = True)

	Show_Hover_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Hover_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)

	Show_Large_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)
	Show_Large_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'Shows_pics', blank = True)

	Show_Title_1 = models.CharField(max_length = 100, blank = True)
	Show_Title_2 = models.CharField(max_length = 100, blank = True)
	Show_Title_3 = models.CharField(max_length = 100, blank = True)
	Show_Title_4 = models.CharField(max_length = 100, blank = True)
	Show_Title_5 = models.CharField(max_length = 100, blank = True)
	Show_Title_6 = models.CharField(max_length = 100, blank = True)
	Show_Title_7 = models.CharField(max_length = 100, blank = True)
	Show_Title_8 = models.CharField(max_length = 100, blank = True)
	Show_Title_9 = models.CharField(max_length = 100, blank = True)
	Show_Title_10 = models.CharField(max_length = 100, blank = True)

	Show_Date_1 = models.CharField(max_length = 100, blank = True)
	Show_Date_2 = models.CharField(max_length = 100, blank = True)
	Show_Date_3 = models.CharField(max_length = 100, blank = True)
	Show_Date_4 = models.CharField(max_length = 100, blank = True)
	Show_Date_5 = models.CharField(max_length = 100, blank = True)
	Show_Date_6 = models.CharField(max_length = 100, blank = True)
	Show_Date_7 = models.CharField(max_length = 100, blank = True)
	Show_Date_8 = models.CharField(max_length = 100, blank = True)
	Show_Date_9 = models.CharField(max_length = 100, blank = True)
	Show_Date_10 = models.CharField(max_length = 100, blank = True)

	Show_Description_1 = models.TextField( blank = True)
	Show_Description_2 = models.TextField(blank = True)
	Show_Description_3 = models.TextField(blank = True)
	Show_Description_4 = models.TextField(blank = True)
	Show_Description_5 = models.TextField(blank = True)
	Show_Description_6 = models.TextField(blank = True)
	Show_Description_7 = models.TextField(blank = True)
	Show_Description_8 = models.TextField(blank = True)
	Show_Description_9 = models.TextField(blank = True)
	Show_Description_10 = models.TextField(blank = True)
	Show_Description_11 = models.TextField( blank = True)
	Show_Description_12 = models.TextField(blank = True)
	Show_Description_13 = models.TextField(blank = True)
	Show_Description_14 = models.TextField(blank = True)
	Show_Description_15 = models.TextField(blank = True)
	Show_Description_16 = models.TextField(blank = True)
	Show_Description_17 = models.TextField(blank = True)
	Show_Description_18 = models.TextField(blank = True)
	Show_Description_19 = models.TextField(blank = True)
	Show_Description_20 = models.TextField(blank = True)

	def __str__(self):
		return self.name

class Sust(models.Model):

	name = models.CharField(max_length = 100, blank = True)

	Sust_Blurb_1 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_2 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_3 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_4 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_5 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_6 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_7 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_8 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_9 = models.CharField(max_length = 100, blank = True)
	Sust_Blurb_10 = models.CharField(max_length = 100, blank = True)

	Sust_Small_Pic_1 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True, null = True)
	Sust_Small_Pic_2 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_3 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_4 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_5 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_6 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_7 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_8 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_9 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)
	Sust_Small_Pic_10 = models.ImageField(default='static/images/location.png', upload_to = 'Susts_pics', blank = True)

	Sust_Hover_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Hover_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)

	Sust_Large_Pic_1 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_2 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_3 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_4 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_5 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_6 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_7 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_8 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_9 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)
	Sust_Large_Pic_10 = models.ImageField(default='/static/images/150.png', upload_to = 'Susts_pics', blank = True)

	Sust_Title_1 = models.CharField(max_length = 100, blank = True)
	Sust_Title_2 = models.CharField(max_length = 100, blank = True)
	Sust_Title_3 = models.CharField(max_length = 100, blank = True)
	Sust_Title_4 = models.CharField(max_length = 100, blank = True)
	Sust_Title_5 = models.CharField(max_length = 100, blank = True)
	Sust_Title_6 = models.CharField(max_length = 100, blank = True)
	Sust_Title_7 = models.CharField(max_length = 100, blank = True)
	Sust_Title_8 = models.CharField(max_length = 100, blank = True)
	Sust_Title_9 = models.CharField(max_length = 100, blank = True)
	Sust_Title_10 = models.CharField(max_length = 100, blank = True)

	Sust_Date_1 = models.CharField(max_length = 100, blank = True)
	Sust_Date_2 = models.CharField(max_length = 100, blank = True)
	Sust_Date_3 = models.CharField(max_length = 100, blank = True)
	Sust_Date_4 = models.CharField(max_length = 100, blank = True)
	Sust_Date_5 = models.CharField(max_length = 100, blank = True)
	Sust_Date_6 = models.CharField(max_length = 100, blank = True)
	Sust_Date_7 = models.CharField(max_length = 100, blank = True)
	Sust_Date_8 = models.CharField(max_length = 100, blank = True)
	Sust_Date_9 = models.CharField(max_length = 100, blank = True)
	Sust_Date_10 = models.CharField(max_length = 100, blank = True)

	Sust_Description_1 = models.TextField( blank = True)
	Sust_Description_2 = models.TextField(blank = True)
	Sust_Description_3 = models.TextField(blank = True)
	Sust_Description_4 = models.TextField(blank = True)
	Sust_Description_5 = models.TextField(blank = True)
	Sust_Description_6 = models.TextField(blank = True)
	Sust_Description_7 = models.TextField(blank = True)
	Sust_Description_8 = models.TextField(blank = True)
	Sust_Description_9 = models.TextField(blank = True)
	Sust_Description_10 = models.TextField(blank = True)
	Sust_Description_11 = models.TextField( blank = True)
	Sust_Description_12 = models.TextField(blank = True)
	Sust_Description_13 = models.TextField(blank = True)
	Sust_Description_14 = models.TextField(blank = True)
	Sust_Description_15 = models.TextField(blank = True)
	Sust_Description_16 = models.TextField(blank = True)
	Sust_Description_17 = models.TextField(blank = True)
	Sust_Description_18 = models.TextField(blank = True)
	Sust_Description_19 = models.TextField(blank = True)
	Sust_Description_20 = models.TextField(blank = True)

	def __str__(self):
		return self.name

